export const experiences = [
  {
    id: "1",
    title: "Full Stack Developer",
    company: "Karibu",
    date: "sept. 2021 - Presente",
    description:
      "Desarrollo de aplicación, apis e integración con servicios para tótems de autoatención en oficinas de Chilquinta Energía.",
    skills: [
      "Vue",
      "Nuxt",
      "Electron",
      "Nodejs",
      "Fastify",
      "Docker",
      "DotNet",
      "Jenkins",
      "Elasticsearch",
      "Git",
    ],
  },
  {
    id: "2",
    title: "Full Stack Developer",
    company: "Walmart Chile",
    date: "dic. 2021 - ago.- 2022",
    description:
      "Desarrollo de sistema para la gestión de casos de productos enviados a Servicio Técnico.",
    skills: [
      "Next",
      "NestJS",
      "Typescript",
      "Nodejs",
      "OAuth2",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Git",
    ],
  },
  {
    id: "3",
    title: "Full Stack Developer",
    company: "Corporación Véliz",
    date: "oct. 2020 - oct.- 2021",
    description:
      "Desarrollo de aplicación web para la gestión y optimización de rutas de transporte.",
    skills: [
      "React",
      "ReactAdmin",
      "Javascript",
      "Python",
      "Flask",
      "Docker",
      "Google Maps",
      "PostgreSQL",
      "CircleCI",
      "Git",
    ],
  },
  {
    id: "4",
    title: "Backend Developer",
    company: "Binaural",
    date: "abr. 2019 - oct.- 2020",
    description:
      "Desarrollo de servicios para aplicaciones web.",
    skills: [
      "Python",
      "Flask",
      "Redis",
      "MySQL",
      "Store Procedure",
      "MongoDB",
      "GitLab CI/CD",
      "Git",
    ],
  },
  {
    id: "5",
    title: "Salesforce Developer",
    company: "Xertica México",
    date: "jul. 2017 - mar.- 2019",
    description:
      "Desarrollo de funcionalidades Salesforce para Tecnológico de Monterrey.",
    skills: [
      "Salesforce",
      "Apex",
      "SOQL",
      "Lightning Web Components",
      "Triggers",
      "Workflows",
    ],
  },
];